# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

services: docker
language: go

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm
  - ARCH=arm64

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - make build ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}
  - make test ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}

after_success:
  # uncomment the following line to deploy only when a new git tag is pushed
  # otherwise it will deploy on every push
  # - test ${TRAVIS_TAG} =~ /^v\d+\.\d+\.\d+.*$/ || exit 0
  - echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}
  - go get -v github.com/estesp/manifest-tool
  - make manifest DOCKER_REPO=${DOCKER_REPO}