# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

language: minimal

services: docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm32v6
  - ARCH=arm32v7
  - ARCH=arm64v8
  - ARCH=i386
  - ARCH=ppc64le
  - ARCH=s390x

before_install:
  - mkdir -p ${HOME}/.docker
  # the experimental flag is required to use docker manifest and squash commands
  - echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json

install:
  # current travis-ci images ship with docker version 17.09.0-ce which does not support manifest commands
  - curl -fsSL get.docker.com | sh

script:
  # build and test for specified arch
  - make build ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}

after_success:
  # uncomment this condition in order to restrict pushing to docker repo on new git version tags
  # - if [[ ${TRAVIS_TAG} =~ ^v\d+\.\d+\.\d+.*$ ]] ; then echo deploying tag ${TRAVIS_TAG} ; else exit 0 ; fi
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make release ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO} BUILD_OPTIONS=--squash
  - make release ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO} BUILD_OPTIONS=--squash VCS_TAG=latest
  # the manifest steps will fail by design until all images are present on the docker repo
  - make manifest DOCKER_REPO=${DOCKER_REPO}
  - make manifest DOCKER_REPO=${DOCKER_REPO} VCS_TAG=latest