# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

language: minimal

services: docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm32v6
  - ARCH=arm32v7
  - ARCH=arm64v8

before_install:
  - mkdir -p ${HOME}/.docker
  # the experimental flag is required to use docker manifest commands
  - echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json

install:
  # current travis-ci images ship with docker version 17.09.0-ce which does not support manifest commands
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  # build and test for specified arch
  - make all ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO} BUILD_OPTIONS=--squash

after_success:
  # uncomment this condition in order to restrict pushing to docker repo on new git version tags
  # - if [[ ${TRAVIS_TAG} =~ ^v\d+\.\d+\.\d+.*$ ]] ; then echo deploying tag ${TRAVIS_TAG} ; else exit 0 ; fi
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}
  # pull existing images for all platforms to create an updated manifest
  # this step will fail by design until all images are present on the docker repo
  - make pull ARCH=amd64 DOCKER_REPO=${DOCKER_REPO}
  - make pull ARCH=arm32v6 DOCKER_REPO=${DOCKER_REPO}
  - make pull ARCH=arm32v7 DOCKER_REPO=${DOCKER_REPO}
  - make pull ARCH=arm64v8 DOCKER_REPO=${DOCKER_REPO}
  - make manifest DOCKER_REPO=${DOCKER_REPO}