language: go

services:
  - docker

branches:
  only:
    - master
    - /^[0-9.]+/

env:
  global:
    - DOCKER_REPO=klutchell/unbound
    - VERSION=1.9.0

jobs:
  include:
    - &build
      stage: build, test, and push
      env: ARCH=amd64
      install: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      before_script:
        - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        - BUILD_VERSION=${VERSION}-${TRAVIS_BUILD_NUMBER}
        - VCS_REF=${TRAVIS_COMMIT}
      script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        - docker-compose -p ci build
        - docker-compose -p ci run test sh -c 'dig sigfail.verteiltesysteme.net @unbound -p 53 | grep -q SERVFAIL'
        - docker-compose -p ci run test sh -c 'dig sigok.verteiltesysteme.net @unbound -p 53 | grep -q NOERROR'
        - docker-compose -p ci push unbound
    - <<: *build
      env: ARCH=arm
    - <<: *build
      env: ARCH=arm64
    - &test
      stage: pull and re-test
      env: ARCH=amd64
      install: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      script:
        - docker-compose -p ci pull unbound
        - docker-compose -p ci run test sh -c 'dig sigfail.verteiltesysteme.net @unbound -p 53 | grep -q SERVFAIL'
        - docker-compose -p ci run test sh -c 'dig sigok.verteiltesysteme.net @unbound -p 53 | grep -q NOERROR'
    - <<: *test
      env: ARCH=arm
    - <<: *test
      env: ARCH=arm64
    - &manifest
      stage: push manifest
      env: TARGET=${DOCKER_REPO}:${VERSION}
      install: go get -v github.com/estesp/manifest-tool
      script:
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:ARCH-${VERSION} \
          --target ${TARGET}
    - <<: *manifest
      env: TARGET=${DOCKER_REPO}:latest