language: minimal

services:
  - docker

branches:
  only:
    - master
    - /^[0-9.]+/

env:
  - ARCH=amd64
  - ARCH=arm32v6
  - ARCH=arm64v8

script:
  - VERSION="$(sed -r -n 's/UNBOUND_VERSION="(.+)"/\1/p' Dockerfile.${ARCH})"
  - make build ARCH=${ARCH} VERSION=${VERSION}
  - make test ARCH=${ARCH} VERSION=${VERSION}
  - make push ARCH=${ARCH} VERSION=${VERSION}

jobs:
  include:
    - stage: deploy
      env: ARCH=amd64
      install: curl -sSL https://github.com/estesp/manifest-tool/releases/download/v1.0.0-rc/manifest-tool-linux-amd64 -o manifest-tool && chmod +x manifest-tool
      script: ./manifest-tool push from-spec manifest.yml