language: go

services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  global:
    - DOCKER_REPO=klutchell/unbound
    - APP_VERSION=1.9.0
    - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - BUILD_VERSION=${APP_VERSION}-${TRAVIS_BUILD_NUMBER}
    - VCS_REF=${TRAVIS_COMMIT}

jobs:
  include:

    - &build
      stage: 'build, test, and push'
      env: ARCH=amd64
      script:
        - echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - make Dockerfile.${ARCH} ARCH=${ARCH}
        - docker-compose -p ci build
        - docker-compose -p ci run tests
        - docker-compose -p ci push unbound

    - <<: *build
      env: ARCH=arm
      install: &qemu-user-static docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - <<: *build
      env: ARCH=arm64
      install: *qemu-user-static

    - &retest
      stage: pull and re-test
      env: ARCH=amd64
      script:
        - docker-compose -p ci pull unbound
        - docker-compose -p ci build tests
        - docker-compose -p ci run tests

    - <<: *retest
      env: ARCH=arm
      install: *qemu-user-static

    - <<: *retest
      env: ARCH=arm64
      install: *qemu-user-static

    - &manifest
      stage: push manifest
      env: TARGET=${DOCKER_REPO}:${APP_VERSION}
      install: go get -v github.com/estesp/manifest-tool
      script:
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:${APP_VERSION}-ARCH \
          --target ${TARGET}

    - <<: *manifest
      env: TARGET=${DOCKER_REPO}:latest