# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

services: docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

before_install:
  - mkdir -p ${HOME}/.docker
  - echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json # needed to use docker manifest

install:
  - docker --version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  - make all ARCH=amd64 DOCKER_REPO=${DOCKER_REPO}
  - make all ARCH=arm32v6 DOCKER_REPO=${DOCKER_REPO}
  - make all ARCH=arm32v7 DOCKER_REPO=${DOCKER_REPO}
  - make all ARCH=arm64v8 DOCKER_REPO=${DOCKER_REPO}

after_success:
  # - if [[ ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]] ; then echo deploying tag ${TRAVIS_TAG} ; else exit 0 ; fi
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push ARCH=amd64 DOCKER_REPO=${DOCKER_REPO}
  - make push ARCH=arm32v6 DOCKER_REPO=${DOCKER_REPO}
  - make push ARCH=arm32v7 DOCKER_REPO=${DOCKER_REPO}
  - make push ARCH=arm64v8 DOCKER_REPO=${DOCKER_REPO}
  - make manifest DOCKER_REPO=${DOCKER_REPO}