language: go

services:
  - docker

branches:
  only:
    - master
    - /^[0-9.]+/

env:
  global:
    - DOCKER_REPO=klutchell/unbound
    - VERSION=1.9.0
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  matrix:
    - ARCH=amd64
    - ARCH=arm
    - ARCH=arm64

jobs:
  include:
    - stage: build
      script:
        - make build ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - make test ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        - make push ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
    - stage: test
      script:
        - docker pull ${DOCKER_REPO}:${ARCH}-${VERSION}
        - make test ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - docker inspect ${DOCKER_REPO}:${ARCH}-${VERSION} | grep ${VERSION}-${BUILD_NUMBER}
    - stage: deploy
      env: ARCH=amd64
      install: go get -v github.com/estesp/manifest-tool
      script:
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:ARCH-${VERSION} \
          --target ${DOCKER_REPO}:${VERSION}
        - manifest-tool inspect ${DOCKER_REPO}:${VERSION}
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:ARCH-${VERSION} \
          --target ${DOCKER_REPO}:latest
        - manifest-tool inspect ${DOCKER_REPO}:latest