services:
  - docker

language: minimal

sudo: required

# if: branch =~ /^[0-9.]+/

jobs:
  include:
    - env: ARCH=amd64
      script:
        - make build ARCH=${ARCH}
        - make test ARCH=${ARCH}
    - env: ARCH=arm32v6
      script:
        - make build ARCH=${ARCH}
        - make test ARCH=${ARCH}
    - env: ARCH=arm64v8
      script:
        - make build ARCH=${ARCH}
        - make test ARCH=${ARCH}
    - stage: deploy
      script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        - make push ARCH=amd64
        - make push ARCH=arm32v6
        - make push ARCH=arm64v8
        - curl -sSL https://github.com/estesp/manifest-tool/releases/download/v1.0.0-rc/manifest-tool-linux-amd64 -o manifest-tool && chmod +x manifest-tool
        - ./manifest-tool push from-spec manifest.yml