services: docker
language: go

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm
    - ARCH=arm64

install:
  - echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - make build ARCH=${ARCH} BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - make test ARCH=${ARCH}

deploy:
  - provider: script
    script: make push ARCH=${ARCH}

jobs:
  include:
    - stage: manifest
      install: go get -v github.com/estesp/manifest-tool
      script: manifest-tool --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} push from-spec manifest.yml