language: minimal

sudo: required

services:
  - docker

env:
  - ARCH=amd64
  - ARCH=armhf
  - ARCH=arm64

install: docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - make build ARCH=${ARCH}
  - make test ARCH=${ARCH}

after_success:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - make push ARCH=${ARCH}