services: docker
language: go

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=armhf
  - ARCH=arm64

script:
  - make build ARCH=${ARCH} BUILD_VERSION=1.9.0-${TRAVIS_BUILD_NUMBER}
  - make test ARCH=${ARCH}

after_success:
  - echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push ARCH=${ARCH}
  - go get -v github.com/estesp/manifest-tool
  - make manifest || true
