language: go

services:
  - docker

branches:
  only:
    - master
    - /^[0-9.]+/

env:
  global:
    - DOCKER_REPO=klutchell/unbound
    - VERSION=1.9.0
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

jobs:
  include:
    - env: ARCH=amd64
      &build
      stage: build
      script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        - make build ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - make test ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - make push ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
    - env: ARCH=arm
      <<: *build
    - env: ARCH=arm64
      <<: *build
    - env: ARCH=amd64
      &test
      stage: test
      script:
        - docker pull ${DOCKER_REPO}:${ARCH}-${VERSION}
        - make test ARCH=${ARCH} VERSION=${VERSION} BUILD_NUMBER=${BUILD_NUMBER}
        - docker inspect ${DOCKER_REPO}:${ARCH}-${VERSION} | grep ${VERSION}-${BUILD_NUMBER}
    - env: ARCH=arm
      <<: *test
    - env: ARCH=arm64
      <<: *test
    - stage: deploy
      install: go get -v github.com/estesp/manifest-tool
      script:
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:ARCH-${VERSION} \
          --target ${DOCKER_REPO}:${VERSION}
        - manifest-tool inspect ${DOCKER_REPO}:${VERSION}
        - |
          manifest-tool --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}" push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_REPO}:ARCH-${VERSION} \
          --target ${DOCKER_REPO}:latest
        - manifest-tool inspect ${DOCKER_REPO}:latest