services: docker
language: go

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm
  - ARCH=arm64

install: go get -v github.com/estesp/manifest-tool

before_script: echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_USERNAME}" --password-stdin

script: make release ARCH=${ARCH} BUILD_LABEL=${TRAVIS_BUILD_NUMBER}

after_success: make manifest || true
