services:
  - docker

language: minimal

sudo: required

# if: branch =~ /^[0-9.]+/

jobs:
  include:
    - env: ARCH=amd64
      script:
        - make build ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
        - make test ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
    - env: ARCH=armhf
      script:
        - make build ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
        - make test ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
    - env: ARCH=arm64
      script:
        - make build ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
        - make test ARCH=${ARCH} VERSION=${TRAVIS_BRANCH}
    - stage: deploy
      script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        - make push ARCH=amd64
        - make push ARCH=armhf
        - make push ARCH=arm64
        - curl -sSL https://github.com/estesp/manifest-tool/releases/download/v1.0.0-rc/manifest-tool-linux-amd64 -o manifest-tool && chmod +x manifest-tool
        - ./manifest-tool push from-spec manifest.yml