version: '3'
services:

    unbound:
        image: klutchell/unbound:${IMAGE_TAG}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ARCH
                - BUILD_DATE
                - BUILD_VERSION
                - VCS_REF

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - unbound
        command:
            - "/bin/sh"
            - -ecx
            - |
                sleep 5 && \
                drill -D @unbound sigfail.verteiltesysteme.net | grep SERVFAIL && \
                drill -D @unbound sigok.verteiltesysteme.net | grep NOERROR
