version: '3'
services:

    unbound:
        image: ${DOCKER_REPO}:${APP_VERSION}-${ARCH}
        build:
            context: .
            dockerfile: Dockerfile.${ARCH}
            args:
                - BUILD_DATE
                - BUILD_VERSION
                - VCS_REF

    tests:
        build: tests
        links:
            - unbound