version: '3'
services:

    unbound:
        image: ${DOCKER_REPO}:${ARCH}-${VERSION}
        build:
            context: .
            dockerfile: Dockerfile.${ARCH}
            args:
                - BUILD_DATE
                - BUILD_VERSION
                - VCS_REF

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - unbound