version: '3'
services:

    unbound:
        image: klutchell/unbound:1.9.0-${ARCH}
        build:
            context: .
            dockerfile: Dockerfile.${ARCH}
            args:
                - BUILD_DATE
                - BUILD_VERSION=1.9.0-${BUILD_LABEL}
                - VCS_REF

    drill:
        build:
            context: .
            dockerfile: Dockerfile.drill
        links:
            - unbound
        command: sh -c 'sleep 10 && /drill.sh unbound'