version: '3'
services:

    unbound:
        image: ${IMAGE_NAME}
        build:
            context: .
            dockerfile: Dockerfile.${ARCH}
            args:
                - BUILD_DATE
                - BUILD_VERSION
                - VCS_REF

    test:
        build:
            context: .
            dockerfile: Dockerfile.ci
        links:
            - unbound