version: '3'
services:

    unbound:
        image: klutchell/unbound:1.9.0-${ARCH}
        build:
            context: .
            dockerfile: Dockerfile.${ARCH}
            args:
                - BUILD_DATE
                - BUILD_VERSION=1.9.0-${BUILD_LABEL}
                - VCS_REF

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - unbound
