version: '3'
services:

    unbound:
        image: klutchell/unbound:1.9.0-${GOARCH}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ARCH
                - BUILD_DATE
                - BUILD_VERSION=1.9.0-${BUILD_TAG}
                - VCS_REF

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - unbound
